services:
  ml-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-ml-backend
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  next-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: churn-next-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - ml-backend
    restart: unless-stopped
